Nams : Tamanna Shaikh

Roll No : 24102A2006

Branch : CMPN -A

Title : ***Sequences***

## Sequences

A sequence is a set of related numbers, events, movements, or items that follow each other in a particular order.

The regular sequences can be generated in R.

### Syntax

`seq()`

`seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)), length.out = NULL, along.with = NULL, ...)`

### Help for seq

In [3]:
seq()

[1] 1

## Sequences

### Continuous sequences with constant unit increment and decrement

In [4]:
1:10
10:1
5:15
15:5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [5]:
-1:-10
-10:-1
-5:-15
-15:-5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [6]:
1.23:10
1.23:10.54
10.54:2.23

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [7]:
-1.23:-10
-5.23:6

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

## Sequences

`seq(10)` is the same as `seq(1:10)`.

In [8]:
seq(10)
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

## Sequences with a predefined variable and constant increment

In [9]:
x=2
seq(1, x, x/10)

x=50
seq(0, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

 [1]  0  5 10 15 20 25 30 35 40 45 50

## Outcome of sequences can be stored.

In [10]:
x = seq(1, 50, 1/2)
x

y=2*x
y

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

## Sequences: Index vector

Assignment of an index-vector.

In [11]:
x = c(9,8,7,6)
ind = seq(along=x)
ind

[1] 1 2 3 4

Accessing a value in the vector through index vector.

Accessing an element of an index-vector.

In [12]:
x[ ind[2] ]

[1] 8

## Sequences — Generating sequences of dates

Generating current time and date.

`Sys.time()` command provides the current time and date from the computer system.

In [13]:
Sys.time()

[1] "2026-09-03 04:11:43 UTC"

`Sys.Date()` command provides the current date from the computer system.

In [14]:
Sys.Date()

[1] "2026-09-03"

# Foundations of R Software — Lecture 27
## Sequences of Dates and Alphabets

Shalabh  
Department of Mathematics and Statistics  
Indian Institute of Technology Kanpur

## Sequences

The regular sequences can be generated in R.

### Syntax

`seq()`

`seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)), length.out = NULL, along.with = NULL, ...)`

In [15]:
seq()

[1] 1

## Sequences — Generating sequences of dates

### Usage

`seq(from, to, by, length.out = NULL, along.with = NULL, ...)`

### Arguments

- `from` — starting date (Required)
- `to` — end date (Optional)
- `by` — increment of the sequence. `"day"`, `"week"`, `"month"`, `"quarter"` or `"year"`.
- `length.out` — integer, optional. Desired length of the sequence.
- `along.with` — take the length from the length of this argument.

### Sequence of first day of years

In [16]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

### Sequence of days

In [17]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

### Sequence of months

In [18]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

### Sequence by years

In [19]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

### To find sequence with defining start and end dates

In [20]:
startdate = as.Date("2016-1-1")
enddate = as.Date("2017-1-1")
out = seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

## Sequences — Generating sequences of alphabets

`letters` is used to find sequence of lowercase alphabets.

In [21]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

`letters[from_index:to_index]` is used to find sequence of lowercase alphabets from a particular index to a specified index.

In [22]:
letters[1:3]
letters[3:1]
letters[21:23]
letters[2]

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "u" "v" "w"

[1] "b"

`LETTERS` is used to find sequence of uppercase alphabets.

In [23]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

`LETTERS[from_index:to_index]` is used to find sequence of uppercase alphabets from a particular index to a specified index.

In [24]:
LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

# Foundations of R Software — Lecture 28
## Repeats

Shalabh  
Department of Mathematics and Statistics  
Indian Institute of Technology Kanpur

## Repeats

The `rep()` function replicates numeric values, or text, or the values of a vector for a specific number of times.

Command `rep` is used to replicates the values in a vector.

### Syntax

`rep(x)` replicates the values in a vector x.

`rep(x, times=n)` # Repeat x as a whole n times

`rep(x, each=n)` # Repeat each cell n times

Following commands repeat each cell for the desired length of the output vector.

`rep(x, length.out=n)`

`rep(x, length=n)`

`rep_len(x, length.out)`

In [25]:
help("rep")

## The command rep

Repeat an object n−times:

In [26]:
rep(3.5, times=10)
rep(1:4, 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

Repeat an object n−times:

`rep(x, times = n)`

Repeat each cell n−times:

`rep(x, each = n)`

In [27]:
x = 1:4
x
rep(x, times = 3)
rep(x, each = 3)

[1] 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

Every object is repeated several times successively:

In [28]:
rep(1:4, each = 2)
rep(1:4, each = 2, times = 3)
rep(1:4, times = 3, each = 2)

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

Observe the effect of ordering of each and times.

Every object is repeated a different number of times:

In [29]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

Every object is repeated a different number of times:

In [30]:
ans = seq(from=2, to=8, by=2)
ans
rep(1:4, ans)

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

In [31]:
x = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x
rep(x, 3)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

## Repetition of characters

In [32]:
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

## Repetition of characters for pre-specified length

In [33]:
rep(2, length.out=5)
rep(2, length=5)
rep(c(2,3), length=5)
rep(c(2,3,4), length=5)

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

In [34]:
rep("apple", length=5)
rep(c("a", "b", "c"), length=2)
rep(c("a", "b", "c"), length=5)

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b"

[1] "a" "b" "c" "a" "b"

# Foundations of R Software — Lecture 29
## Sorting, Ordering and Mode

Shalabh  
Department of Mathematics and Statistics  
Indian Institute of Technology Kanpur

## Sorting

sort function sorts the values of a vector in ascending order (by default) or descending order.

### Syntax

`sort(x, decreasing = FALSE, ..,)`

`sort(x, decreasing = FALSE, na.last = NA, ...)`

- `x` — Vector of values to be sorted
- `decreasing` — Should the sort be increasing or decreasing
- `na.last` — for controlling the treatment of NAs.
  - If TRUE, missing values in the data are put last;
  - if FALSE, they are put first;
  - if NA, they are removed.

In [35]:
y = c(8,5,7,6)
y
sort(y)
sort(y, decreasing = TRUE)

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

## Ordering

order function sorts a variable according to the order of variable.

### Syntax

`order(x, decreasing = FALSE, ..,)`

`order(x, decreasing = FALSE, na.last = TRUE, ...)`

- `x` — Vector of values to be sorted
- `decreasing` — Should the sort be increasing or decreasing
- `na.last` — for controlling the treatment of NAs.
  - If TRUE, missing values in the data are put last;
  - if FALSE, they are put first;
  - if NA, they are removed.

### Example

Value: 9 8 5 7 6  
Position: 1 2 3 4 5

Ordered value: 5 6 7 8 9  
Position: 3 5 4 2 1

In [36]:
y = c(9,8,5,7,6)
y
order(y)
order(y, decreasing = TRUE)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

## Mode

Every object has a mode.

The mode indicates how the object is stored in memory:

- number
- character string
- list of pointers to other objects
- function etc.

`mode` function gives us such information.

### Syntax

`mode()`

In [37]:
mode(2.432)
mode(c(3,4,5,6,7,8))
mode("India")
mode(c("India", "CANADA"))

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

### Mode — examples

| Object | Example | Mode |
|---|---|---|
| Number | `1.234` | numeric |
| Vector of numbers | `c(6, 7, 8, 9)` | numeric |
| Character string | `"India"` | character |
| Vector of character strings | `c("India", "CANADA")` | character |
| Factor | `factor(c("MP", "UP"))` | numeric |
| List | `list("India","CANADA")` | list |
| Data frame | `data.frame(x=1:2, y=c("India","CANADA"))` | list |
| Function | `print` | function |

In [38]:
mode(factor(c("UP", "MP")) )
mode(list("India", "USA"))
mode(data.frame(x=1:2, y=c("India", "USA")))
mode(print)

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

# Foundations of R Software — Lecture 30
## Lists

Shalabh  
Department of Mathematics and Statistics  
Indian Institute of Technology Kanpur

## Lists

Vectors, matrices, and arrays is that each of these types of objects may only contain one type of data.

For example, a vector may contain all numeric data or all character data.

A list is a special type of object that can contain data of multiple types.

Lists are characterized by the fact that their elements do not need to be of the same object type.

## Lists

- Lists can contain elements of different types so that the list elements may have different modes.
- Lists can even contain other structured objects, such as lists and data frames which allows to create recursive data structures.
- Lists can be indexed by position.

So `x[[5]]` refers to the fifth element of x.

## Lists

- Lists can extract sublists.

  So `x[c(2,5)]` is a sublist of x that consists of the second and fifth elements.

- List elements can have names.

  Both `x[["Students"]]` and `x$Students` refer to the element named `"Students"`.

- Difference between a vector and a list:
  - In a vector, all elements must have the same mode.
  - In a list, the elements can have different modes.

## Example

In [39]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1
x2
x1+x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

## Example

In [40]:
x1[2,1] = "hello"
x1
x1 + x2

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

ERROR: Error in x1 + x2: non-numeric argument to binary operator

The last command is intentionally kept as in the PDF and is expected to produce the non-numeric argument to binary operator error shown in the notes.

## Lists

Lists can contain any kind of objects as well as objects of different types. For example, lists can contain matrices as objects.

In [41]:
x1 = matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2 = matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1
x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

## Example

In [42]:
matlist = list(x1, x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## Example

In [43]:
matlist[1]
matlist[2]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## An example of a list that contains different object types:

In [44]:
z1 = list( c("water", "juice", "lemonade"),
rep(1:4, each=2), matrix(data=5:8, nrow=2,
ncol=2, byrow=T) )
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## Lists

Access the elements of a list using the operator `[[]]`.

Following commands work.

In [45]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

Suppose we want to extract "juice". The command below returns NULL instead of "juice", while the next command returns the desired result.

Notice the positions of brackets.

In [46]:
z1[1][2]

[[1]]
NULL

In [47]:
z1[[1]][2]

[1] "juice"

***~ Thank you -- ***