Name : Tamanna Shaikh

Roll No : 24102A2006

R Programming  

Week 9

# R Programming 

## Foundations of R Software

**Strings — Display, Formatting, Paste, Splitting and Manipulation**

## Strings: Display and Formatting

In [1]:
print("The zero occurs at"); print(2*pi); print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

In [2]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

In [3]:
d = date()
cat("Today’s date is:", d, "\n" )

Today’s date is: Thu Oct  1 03:40:36 2026

In [4]:
x = 1:10
x
cat(x, sep =" ++ ")
cat("\n")
cat(x, sep =" / ")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

In [5]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

In [6]:
cat("The square root of",x,"is approximately", format(sqrt(x),digits=3),"\n")

The square root of 7 is approximately 2.65

In [7]:
evenno = c(2,4,6,8,10)
evenno
cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

In [8]:
x = 1:10
x
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

 [1]  1  2  3  4  5  6  7  8  9 10

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

## Strings: Paste Function

In [9]:
paste(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [10]:
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

In [11]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

In [12]:
paste("Everybody", "loves", "R Programming.", sep="*")

[1] "Everybody*loves*R Programming."

In [13]:
paste("Everybody", "loves", "R Programming.", sep="===")

[1] "Everybody===loves===R Programming."

In [14]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

In [15]:
names = c("Prof. Singh", "Mr. Venkat", "Dr. Jha")
paste(names, "is", "a good", "person.", collapse=", and ")

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

In [16]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")

[1] "1# is first#2# is second#3# is third"

In [17]:
paste(1, " is first ", 2, " is second ", 3, " is third ", sep = "#")

[1] "1# is first #2# is second #3# is third "

In [18]:
x = paste("Ex", 1:5, sep="_")
x
x[1]
x[2]
x[3]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

In [19]:
x = paste("Ex", 1:5, sep="_", collapse="")
x[1]

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [20]:
x = paste("Ex", 1:5, sep="_")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [21]:
x = paste("Ex", 1:5, sep="_", collapse="")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

In [22]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

In [23]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

In [24]:
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

## Lecture 38 — Strings: String Splitting

In [25]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split="!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

In [26]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split = "&!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

In [27]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
y = strsplit(x, split = "!&")
y

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

In [28]:
y[[1]][1]
y[[1]][2]
y[[1]][3]

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

In [29]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
datesplt = strsplit(dates, "-")
datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

In [30]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol=3, byrow=TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

In [31]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol=3, byrow=TRUE)
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

In [32]:
strsplit("Shalabh",split="")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

## Manipulations with Strings and Alphabets

In [33]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nchar(x)
nchar(y)

[1] 19

[1] 26

In [34]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

In [35]:
x = c("Apple", "Banana", "Cake")
x
nzchar(x)
y = c("Apple", "", "Cake")
y
nzchar(y)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

In [36]:
x = c("Apple", "Banana", "Cake")
nchar(x)
y = c(2, 4, 6)
nchar(y)
z = c(11, 222, 3333)
nchar(z)
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 5 6 4

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

In [37]:
x = "R course will start from 24.07.2022"
toupper(x)
z = "INDIAN INSTITUTE OF TECHNOLOGY"
tolower(z)

[1] "R COURSE WILL START FROM 24.07.2022"

[1] "indian institute of technology"