Name : Tamanna Shaikh

Roll No: 24102A2006



*R-Programming*

**Lab 5**

 ***Missing Data Handling***

***Missing Data***

In [ ]:
x=NA

In [ ]:
is.na(x)

[1] TRUE

In [ ]:
x = c(11, NA, 13, NA)

In [ ]:
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

***Example : How to work with missing data***

In [ ]:
x = c(11,NA,13, NA)

In [ ]:
mean(x)

[1] NA

In [ ]:
mean(x, na.rm = TRUE)

[1] 12

***NA versus NULL***

In [ ]:
#NA is a placeholder for something that exists but is missing.
#NULL stands for something that never existed at all

***Location of missing values***

To identify the location of NAs,

use which() function as
"which(is.na( ))"

In [ ]:
 x = c(11,NA,13,NA)

In [ ]:
x

[1] 11 NA 13 NA

In [ ]:
which (is.na(x))

[1] 2 4

To count of NAs the number of NAs , use sum() function as
sum(is.na( ))

In [ ]:
sum(is.na(x))

[1] 2

***Finding complete cases***

In [ ]:
 x = c(11,NA,13,NA)

In [ ]:
x

[1] 11 NA 13 NA

In [ ]:
complete.cases(x)

[1]  TRUE FALSE  TRUE FALSE

Finding complete data set

In [ ]:
x = c(11,NA,13,NA)

In [ ]:
x

[1] 11 NA 13 NA

In [ ]:
y =   na.omit(x)

In [ ]:
y

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

In [ ]:
x = c(11,NA,13,NA)

In [ ]:
mean(x)

[1] NA

In [ ]:
mean(y)

[1] 12

***Conditional Executions – If and If‐Else***

In [ ]:
x=5

In [ ]:
if (x>4) x*3

[1] 15

In [ ]:
x=3

In [ ]:
if (x>4) x*3    #no response will be obtained

In [ ]:
x = 6

In [ ]:
if(x>3) {
  print ("The value is more than 3")
}

[1] "The value is more than 3"

In [ ]:
if(x>3) {
  print ("The value is more than 3")
}

[1] "The value is more than 3"

In [ ]:
x = 5

In [ ]:
if ( x==3) { x = x-1} else { x=2*x}

In [ ]:
x

[1] 10

In [ ]:
x=3

In [ ]:
if ( x==3){x=x-1}else(x=2*x)

In [ ]:
x

[1] 2

In [ ]:
 x= 6
if(x > 3){
print("The value is more than 3")
} else {
print("The value is less than 3")
}

[1] "The value is more than 3"

In [ ]:
 x= 2
if(x > 3){
print("The value is more than 3")
} else {
print("The value is less than 3")
}

[1] "The value is less than 3"

***Nested if else if and ifelse***

In [ ]:
x = 5
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 10

In [ ]:
x = 2
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 7

In [ ]:
x = 3
if ( x==3 ) {
x = x-1
} else if ( x < 3 ) {
x = x+5
} else { x = 2*x }
x

[1] 2

In [ ]:
x = 1:10

In [ ]:
x

 [1]  1  2  3  4  5  6  7  8  9 10

In [ ]:
ifelse ( x<6,x^2,x+1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [ ]:
x=c(7,9,8,4)

***Switch and which commands***

In [ ]:
switch("colour", "colour
" = "blue", "gender" =
"male", "volume" = 50)

In [ ]:
switch("volume", "colour
" = "blue", "gender" =
"male", "volume" = 50)

[1] 50

In [ ]:
switch(4,"apple", "banana", "orange")

In [ ]:
switch("size", "colour" = "blue", "gender" =
"male", "volume" = 50)

In [ ]:
x = c(10,15,8,14,6,12)
 x

[1] 10 15  8 14  6 12

In [ ]:
which(x==14)

[1] 4

In [ ]:
which(x!=12)

[1] 1 2 3 4 5

In [ ]:
which(x>10)

[1] 2 4 6

In [ ]:
x=matrix(nrow=3,ncol=3,data=1:9)

In [ ]:
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which.min(x)

[1] 1

In [ ]:
which.max(x)

[1] 9

In [ ]:
x=matrix(nrow=3,ncol=3,data=1:9)

In [ ]:
x

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

In [ ]:
which(x%%2==4)

integer(0)

In [ ]:
which(x%%2==1,arr.ind=TRUE)

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3

***-- THANK YOU ---***