# Name: Tamanna Shaikh
# Roll No: 24102A2006
# Branch: CMPN -A
# Experiment Tittle: Missing Data Handling and Conditional Executions in R

## Lecture 18: Missing Data Handling

### 1. Assign a missing value (NA) to a variable

In [1]:
x = NA
x
is.na(x)

[1] NA

[1] TRUE

### 2. Identify missing values in a vector using is.na()

In [2]:
x = c(11, NA, 13, NA)
x
is.na(x)

[1] 11 NA 13 NA

[1] FALSE  TRUE FALSE  TRUE

### 3. Calculate mean with and without removing missing values

In [3]:
x = c(11, NA, 13, NA)

mean(x)
mean(x, na.rm = TRUE)

[1] NA

[1] 12

### 4. Distinguish between NA and NULL

In [4]:
x = NA
y = NULL

x
y
is.na(x)
is.null(y)

[1] NA

NULL

[1] TRUE

[1] TRUE

### 5. Find the locations of missing values using which(is.na())

In [5]:
x = c(11, NA, 13, NA)
x
which(is.na(x))

[1] 11 NA 13 NA

[1] 2 4

### 6. Count the number of missing values using sum(is.na())

In [6]:
x = c(11, NA, 13, NA)
x
sum(is.na(x))

[1] 11 NA 13 NA

[1] 2

### 7. Find complete cases using complete.cases()

In [7]:
x = c(11, NA, 13, NA)
x
complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

### 8. Remove missing values using na.omit()

In [8]:
x = c(11, NA, 13, NA)
x
y = na.omit(x)
y

[1] 11 NA 13 NA

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

### 9. Calculate the mean before and after removing missing values

In [9]:
x = c(11, NA, 13, NA)
y = na.omit(x)

mean(x)
mean(y)

[1] NA

[1] 12

## Lecture 19: Conditional Execution – if and if-else

### 10. Use a simple if statement when the condition is TRUE

In [10]:
x = 5

if (x > 4) x * 3

[1] 15

### 11. Use a simple if statement when the condition is FALSE

In [11]:
x = 3

if (x > 4) x * 3

### 12. Use if statement with braces when the condition is TRUE

In [12]:
x = 5

if (x > 4) {
  x * 3
}

[1] 15

### 13. Use if statement with braces when the condition is FALSE

In [13]:
x = 3

if (x > 4) {
  x * 3
}

### 14. Print a message when a value is more than 3

In [14]:
x = 6

if (x > 3) {
  print("The value is more than 3")
}

[1] "The value is more than 3"

### 15. Check a condition that is FALSE using if

In [15]:
x = 2

if (x > 3) {
  print("The value is more than 3")
}

### 16. Use if-else when x is not equal to 3

In [16]:
x = 5

if (x == 3) {
  x = x - 1
} else {
  x = 2 * x
}

x

[1] 10

### 17. Use if-else when x is equal to 3

In [17]:
x = 3

if (x == 3) {
  x = x - 1
} else {
  x = 2 * x
}

x

[1] 2

### 18. Print whether a value is more than or less than 3

In [18]:
x = 6

if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is more than 3"

### 19. Print the result for a value less than 3

In [19]:
x = 2

if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] "The value is less than 3"

## Lecture 20: Nested if-else and ifelse

### 20. Use nested if-else with x greater than 3

In [20]:
x = 5

if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2 * x
}

x

[1] 10

### 21. Use nested if-else with x less than 3

In [21]:
x = 2

if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2 * x
}

x

[1] 7

### 22. Use nested if-else when x is equal to 3

In [22]:
x = 3

if (x == 3) {
  x = x - 1
} else if (x < 3) {
  x = x + 5
} else {
  x = 2 * x
}

x

[1] 2

### 23. Apply ifelse() to a vector of values

In [23]:
x = 1:10
x
ifelse(x < 6, x^2, x + 1)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  4  9 16 25  7  8  9 10 11

### 24. Identify even and odd numbers using ifelse() and modulo operator

In [24]:
x = c(7, 9, 8, 4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

## Lecture 21: switch() and which() for Conditional Execution

### 25. Use switch() with an integer expression

In [25]:
switch(2, "apple", "banana", "orange")
switch(1, "apple", "banana", "orange")

[1] "banana"

[1] "apple"

### 26. Use switch() with a character string and named cases

In [26]:
switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)
switch("volume", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

[1] 50

### 27. Use switch() when there is no matching case

In [27]:
switch(4, "apple", "banana", "orange")
switch("size", "colour" = "blue", "gender" = "male", "volume" = 50)

### 28. Find positions of TRUE elements using which()

In [28]:
x = c(10, 15, 8, 14, 6, 12)
x

which(x == 14)
which(x != 12)
which(x > 10)

[1] 10 15  8 14  6 12

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

### 29. Find minimum and maximum positions in a matrix using which.min() and which.max()

In [29]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x

which.min(x)
which.max(x)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

[1] 9

### 30. Find positions of odd values in a matrix using which()

In [30]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x

which(x %% 2 == 1)
which(x %% 2 == 1, arr.ind = TRUE)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3