# R Programming NPTEL - Practical 3

**Name:** Tamanna Shaikh  
**Roll No:** 24102A2006  
**Branch:** CMPN -A  
**Experiment Tittle:** Basics of Calculations, Built-in Functions and Matrices

## Power operation using ^

Perform a power calculation using the ^ operator.

In [1]:
2^3

[1] 8

## Power operation using **

Perform a power calculation using the ** operator.

In [2]:
2**3

[1] 8

## Fractional power

Calculate a square root using the power operator.

In [3]:
2^0.5

[1] 1.414214

## Negative fractional power

Calculate a negative fractional power.

In [4]:
2^-0.5

[1] 0.7071068

## Power of a data vector

Apply the power operation element-wise to a vector.

In [5]:
c(2,3,5,7)^2

[1]  4  9 25 49

## Power operation with a vector

Apply different exponents element-wise; the shorter vector is recycled.

In [6]:
c(2,3,5,7)^c(2,3)

[1]   4  27  25 343

## Power operation with vectors of different lengths

Apply vectorized powers and observe R's warning when lengths are not multiples.

In [7]:
c(1,2,3,4,5,6)^c(2,3,4)

[1]    1    8   81   16  125 1296

## Power operation with non-multiple lengths

Demonstrate vector recycling and its warning.

In [8]:
c(2,3,5,7)^c(2,3,4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

## Integer division with scalars

Use %/% to perform integer division.

In [9]:
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1

[1] 2

[1] 2

## Integer division with a scalar

Apply integer division to each vector element.

In [10]:
c(2,3,5,7) %/% 2

[1] 1 1 2 3

## Integer division with a data vector

Apply integer division using two vectors and recycling.

In [11]:
c(2,3,5,7) %/% c(2,3)

[1] 1 1 2 2

## Integer division with non-multiple lengths

Demonstrate integer division and the recycling warning.

In [12]:
c(2,3,5) %/% c(2,3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

## Modulo division with scalars

Use %% to find remainders after division.

In [13]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

## Modulo division with a scalar

Find the remainder for each element of a vector.

In [14]:
c(2,3,5,7) %% 2

[1] 0 1 1 1

## Modulo division with data vectors

Find remainders using two vectors with recycling.

In [15]:
c(2,3,5,7) %% c(2,3)

[1] 0 0 1 1

## Modulo division with non-multiple lengths

Demonstrate modulo operation and the recycling warning.

In [16]:
c(2,3,5) %% c(2,3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

## Maximum of values

Use max() to find the maximum value.

In [17]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

## Minimum of values

Use min() to find the minimum value.

In [18]:
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8

[1] -7.8

## Arithmetic mean

Use mean() with separate arguments and with c().

In [19]:
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 2

[1] 3

## Absolute value

Use abs() for scalar and vector values.

In [20]:
abs(-4)
abs(c(-1,-2,-3,4,5))

[1] 4

[1] 1 2 3 4 5

## Square root

Use sqrt() for scalar and vector values.

In [21]:
sqrt(4)
sqrt(c(4,9,16,25))

[1] 2

[1] 2 3 4 5

## Sum of values

Use sum() to calculate the total of vector values.

In [22]:
sum(c(2,3,5,7))

[1] 17

## Product of values

Use prod() to calculate the product of vector values.

In [23]:
prod(c(2,3,5,7))

[1] 210

## Round values

Use round() to round values.

In [24]:
round(1.23)
round(1.83)

[1] 1

[1] 2

## Natural logarithm

Use log() to calculate natural logarithms.

In [25]:
log(10)
log(exp(1))
log(c(10,100,1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

## Base-10 logarithm

Use log10() to calculate base-10 logarithms.

In [26]:
log10(10)
log10(100)
log10(c(10,100,1000))

[1] 1

[1] 2

[1] 1 2 3

## Assignment with variables

Save values in variables and perform a calculation.

In [27]:
x1 = c(1,2,3,4)
x1
x2 = x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

## Calculation with scalar, vector and functions

Combine a vector with sum() and prod() in a calculation.

In [28]:
c(1,2,3,4) + sum(c(1,2,3,4)) * prod(c(1,2))
abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)))

[1] 21 22 23 24

[1] 19 18 17 16

## Creating a 4 x 2 matrix

Create a 4 x 2 matrix using matrix(); values are entered column-wise by default.

In [29]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

## Accessing a matrix element

Access the element in row 3 and column 2.

In [30]:
x[3,2]

[1] 7

## Entering matrix data column-wise

Create a matrix explicitly using byrow = FALSE.

In [31]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=FALSE)
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

## Entering matrix data row-wise

Create a matrix using byrow = TRUE.

In [32]:
y = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8), byrow=TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

## Matrix dimensions

Use dim() to find matrix dimensions.

In [33]:
dim(x)

[1] 4 2

## Number of rows

Use nrow() to find the number of rows.

In [34]:
nrow(x)

[1] 4

## Number of columns

Use ncol() to find the number of columns.

In [35]:
ncol(x)

[1] 2

## Matrix mode

Use mode() to identify the matrix storage mode.

In [36]:
mode(x)

[1] "numeric"

## Matrix attributes

Use attributes() to display matrix attributes.

In [37]:
attributes(x)

$dim
[1] 4 2

## R help for matrix

Open the built-in help for matrix().

In [38]:
help("matrix")

## Testing a matrix

Use is.matrix() to test whether an object is a matrix.

In [39]:
is.matrix(x)

[1] TRUE

## Converting to a matrix

Use as.matrix() and test the converted object.

In [40]:
is.matrix(as.matrix(1:10))

[1] TRUE

## Data-frame and matrix example

Use the warpbreaks example from the PDF to demonstrate data-frame versus matrix conversion.

In [41]:
data(warpbreaks)
!is.matrix(warpbreaks)
warpbreaks[1:10,]
as.matrix(warpbreaks[1:10,])

[1] TRUE

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M

   breaks wool tension
1  26     A    L
2  30     A    L
3  54     A    L
4  25     A    L
5  70     A    L
6  52     A    L
7  51     A    L
8  26     A    L
9  67     A    L
10 18     A    M