# R Programming NPTEL - Practical 4

**Name:** Tamanna Shaikh  
**Roll No:** 24102A2006  
**Branch:** CMPN -A  
**Experiment Tittle:** Matrix Operations, Mathematical Operations and Logical/Relational Operators

## Lecture 13 - Renaming Row and Column Names

Create a 4 × 3 matrix and rename its row and column names using `rownames()` and `colnames()`.

In [1]:
x = matrix(nrow=4, ncol=3, data=c(1:12))
x

rownames(x) = c("r1", "r2", "r3", "r4")
x

colnames(x) = c("c1", "c2", "c3")
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

## Assigning a Specified Number to All Matrix Elements

Create a 4 × 2 matrix in which every element is assigned the value 2.

In [2]:
x = matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

## Construction of a Diagonal Matrix - Identity Matrix

Construct a diagonal identity matrix of dimension 3 using `diag()`.

In [3]:
d = diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

## Construction of a Diagonal Matrix with 5

Construct a 3 × 3 diagonal matrix with all diagonal elements equal to 5.

In [4]:
d = diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

## Lecture 13 - Transpose of a Matrix

Create a 4 × 2 matrix and find its transpose using `t()`.

In [5]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

xt = t(x)
xt

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

## Finding Row and Column Sums

Use `rowSums()` to find the sum of numbers in rows and `colSums()` to find the sum of numbers in columns.

In [6]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

## Finding Row and Column Means

Use `rowMeans()` to find the means of rows and `colMeans()` to find the means of columns.

In [7]:
x = matrix(nrow=4, ncol=2, data=c(1,2,3,4,5,6,7,8))
x

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

## Lecture 14 - Access to Rows, Columns or Submatrices

Create the 5 × 3 matrix used in the NPTEL example.

In [8]:
x = matrix(nrow=5, ncol=3, byrow=T, data=1:15)
x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

## Accessing a Specific Row

Access the third row using `x[3,]`.

In [9]:
x[3,]

[1] 7 8 9

## Accessing a Specific Column

Access the second column using `x[,2]`.

In [10]:
x[,2]

[1]  2  5  8 11 14

## Accessing a Submatrix

Access rows 4 to 5 and columns 2 to 3 using matrix indexing.

In [11]:
x[4:5, 2:3]

     [,1] [,2]
[1,] 11   12
[2,] 14   15

## Accessing Selected Rows and Columns

Access rows 1 and 4 and columns 1 and 3 using `c()`.

In [12]:
x[c(1,4), c(1,3)]

     [,1] [,2]
[1,]  1    3
[2,] 10   12

## Matrix Access Result

The NPTEL example shows that the result `2 5 8 11 14` does not by itself make it possible to know whether the extracted object is intended as a row or a column.

In [13]:
x
x[,2]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1]  2  5  8 11 14

## Addition of a Matrix with a Constant

Every element of the matrix is added with the scalar 5.

In [14]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

x + 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

## Subtraction of a Matrix with a Constant

Every element of the matrix is subtracted by the scalar 5.

In [15]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

x - 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

## Multiplication of a Matrix with a Constant

Every element of the matrix is multiplied by the scalar 5.

In [16]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

5 * x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

## Division of a Matrix with a Constant

Every element of the matrix is divided by the scalar 2.

In [17]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

x / 2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

## Addition and Subtraction of Matrices

Addition and subtraction of matrices of the same dimensions can be performed using the usual `+` and `-` operators.

In [18]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=4, ncol=2, data=11:18, byrow=T)

x
y

x + y
x - y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

## Lecture 15 - Scalar Multiplication and Matrix Expressions

Multiply the matrix by 4, following the NPTEL example.

In [19]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

4 * x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

## Matrix Expressions

Perform the two matrix expressions shown in the NPTEL material.

In [20]:
x + 4*x
4*x - x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

## Multiplication of Matrices

Matrix multiplication is performed using the `%*%` operator. Create matrices with compatible dimensions and multiply them.

In [21]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
y = matrix(nrow=2, ncol=4, data=11:18, byrow=T)

x
y

x %*% y
y %*% x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

## Multiplication of X Transpose and X

Calculate `t(x) %*% x` and `x %*% t(x)`.

In [22]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

t(x)

t(x) %*% x
x %*% t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

## Cross Product of a Matrix

Use `crossprod(x)` to calculate the cross product `X'X`. The NPTEL material notes that `crossprod()` executes this multiplication faster than the conventional `t(x) %*% x` method.

In [23]:
x = matrix(nrow=4, ncol=2, data=1:8, byrow=T)
x

crossprod(x)

# Conventional method for comparison
t(x) %*% x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2]
[1,]  84  100
[2,] 100  120

## Concatenating Matrices Row-wise and Column-wise

`rbind(x, y)` concatenates matrices row-wise, while `cbind(x, y)` concatenates matrices column-wise.

In [24]:
x = matrix(nrow=3, ncol=2, data=1:6, byrow=T)
y = matrix(nrow=3, ncol=2, data=11:16, byrow=T)

x
y

rbind(x, y)
cbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

## Inverse of a Matrix

Use `solve()` with the positive definite matrix from the NPTEL example.

In [25]:
y = matrix(nrow=2, ncol=2, byrow=T,
           data=c(84,100,100,120))
y

solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

## Eigen Values and Eigen Vectors of a Matrix

Use `eigen()` on the same matrix to obtain its eigen values and eigen vectors.

In [26]:
y = matrix(nrow=2, ncol=2, byrow=T,
           data=c(84,100,100,120))
y

eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

## Lecture 16 - Logical Operators and Comparisons

The NPTEL material lists relational and logical operators such as `>`, `>=`, `<`, `<=`, `==`, `!=`, `!`, `&`, `&&`, `|`, `||`, `xor()`, `isTRUE()` and `isFALSE()`.

In [27]:
# Relational operators
8 > 7
7 < 5
7 > 7
7 >= 7
8 < 8
8 <= 8
8 != 9
9 != 9
7 == 7
7 == 8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

## Use of `|` and `||` with a Scalar

Compare the results for the logical OR operators using scalar values.

In [28]:
x = 8
(x < 10) || (x < 2)

x = 18
(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

## Difference Between `|` and `||`

The NPTEL example shows that `||` operates only on the first element, whereas `|` operates on all elements.

In [32]:
x = c(8,18)

(x[1] < 10) || (x[1] < 2)

[1] TRUE

## Use of `&` and `&&` with a Scalar

Compare the logical AND operators using scalar values.

In [33]:
x = 5
(x < 10) && (x > 2)

x = 15
(x < 10) && (x > 2)

[1] TRUE

[1] FALSE

## Difference Between `&` and `&&`

The NPTEL example shows that `&&` operates only on the first element, whereas `&` operates on all elements.

In [35]:
# Define a vector
x = c(8,18)

# Display the vector
x

# Check each element using less than operator
x < 10

# Check each element using greater than operator
x > 2

# Scalar AND operator (&&)
# Use the first element explicitly because && works with a single logical value
(x[1] < 10) && (x[1] > 2)

# Element-wise AND operator (&)
# Checks the condition for each element of the vector
(x < 10) & (x > 2)

[1]  8 18

[1]  TRUE FALSE

[1] TRUE TRUE

[1] TRUE

[1]  TRUE FALSE

## Filtering Values Using `&`

Generate `x = 1:6`, check which values are greater than 2 and less than 5, and then extract those values.

In [36]:
x = 1:6

(x > 2) & (x < 5)

x[(x > 2) & (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

## Filtering Values Using `|`

Check which values are greater than 2 or less than 5 and extract the matching values.

In [37]:
x = 1:6

(x > 2) | (x < 5)

x[(x > 2) | (x < 5)]

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

## Longer Logical Form on a Vector

The NPTEL example demonstrates that `&&` examines only the first element of each vector.

In [39]:
# Create a vector from 1 to 6
x = 1:6

# Display the vector
x

# Check which elements are greater than 2
x > 2

# Check which elements are less than 5
x < 5

# Scalar AND operator (&&)
# Compare only the first element
(x[1] > 2) && (x[1] < 5)

# Element-wise AND operator (&)
# Compare each element of the vector
(x > 2) & (x < 5)

[1] 1 2 3 4 5 6

[1] FALSE FALSE  TRUE  TRUE  TRUE  TRUE

[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE

[1] FALSE

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

## Lecture 17 - Relational Operators and Comparisons

`TRUE` and `FALSE` are logical constants. The NPTEL material also notes that zero is considered `FALSE` and non-zero numbers are taken as `TRUE` in logical contexts.

In [40]:
TRUE
FALSE

as.logical(0)
as.logical(1)
as.logical(5)

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] TRUE

## Logical NOT, Element-wise AND/OR and Long Forms

Demonstrate the logical operators listed in the material.

In [41]:
x = TRUE
y = FALSE

x & y
x | y
!x

[1] FALSE

[1] TRUE

[1] FALSE

## `xor()`, `isTRUE()` and `isFALSE()`

Demonstrate exclusive OR and the tests for TRUE/FALSE.

In [42]:
xor(TRUE, FALSE)
xor(TRUE, TRUE)

isTRUE(TRUE)
isFALSE(TRUE)
isTRUE(FALSE)
isFALSE(FALSE)

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

## Logical Variables from Comparisons

Create logical variables from relational comparisons and test their logical type using `is.logical()`.

In [43]:
x = 5

Logical1 = (x > 2)
Logical1
is.logical(Logical1)

Logical2 = (x < 10)
Logical2
is.logical(Logical2)

Logical3 = (x != 5)
Logical3
is.logical(Logical3)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

## More Logical Comparison Examples

Create additional logical variables using the expressions shown in the NPTEL material.

In [44]:
x = 5

Logical4 = (2*x > 11)
Logical4
is.logical(Logical4)

Logical5 = (3*x < 20)
Logical5
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

## Relational Comparisons with Vectors

Compare corresponding elements of two vectors using relational operators.

In [45]:
x = c(1, 2, 3)
y = c(4, 5, 6)

x > y
x < y
x != y
x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

## `isTRUE()` and `isFALSE()` with Comparisons

Test comparison results using `isTRUE()` and `isFALSE()`.

In [46]:
isTRUE(8 < 6)
isTRUE(8 > 6)

isFALSE(5 < 8)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

## Negation Example

Use `!` to obtain the logical negation of TRUE.

In [47]:
x = TRUE
!x

[1] FALSE

## Conclusion

This practical covers the matrix operations and logical/relational operations presented in the Week 4 NPTEL material, including row and column naming, diagonal matrices, transpose, row/column sums and means, matrix indexing, scalar and matrix arithmetic, matrix multiplication, cross product, concatenation, inverse, eigen values/vectors, logical operators, vector filtering, and relational comparisons.